### ISSUE TITLE
Fresh install fails on Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by dawnarius** [h2oai/h2ogpt#1933]
Hello
Since this project is obviously no longer maintained I can't manage to install it anymore (on a fresh Ubuntu 24.04 LTS with python 3.10 and following the official guides)
Too much errors and conflicts since some packages are actively maintained but not h2ogpt code
Can anyone provide me with list of the correct versions of the used packages? or a clear and working guide to install it on a fresh Ubuntu 24.04 LTS with python 3.10?
Also if anyone has a working version, please do "pip env list" and give me the resulting list
It could really help
Thanks

**Comment by pseudotensor** [comment]
I haven't tried Ubuntu 24 yet, just 22.  Maybe someone else has tried it.

I don't expect any conflicts etc. because most packages are fixed in version that ever had had issues in past.

E.g. you could try docker build but change to Ubuntu 24.  I expect it would work fine.

A separate internal version is maintained and i haven't noticed any issues in any builds.

**Comment by BhoomikaMurali** [comment]
same I am still facing issue , how can i run it on a Ubuntu 22 on a cpu
