### ISSUE TITLE
Can not download a model with current version

### ISSUE THREAD

**Issue by gabriead** [h2oai/h2ogpt#980]
Hi guys,
when I run the client locally and select a model to download (e.g. T5-small, but I have tried different LLama2 models as well)
I am always running into this error:

`Traceback (most recent call last):
  File "C:\Users\adria\h2ogpt\generate.py", line 16, in <module>
    entrypoint_main()
  File "C:\Users\adria\h2ogpt\generate.py", line 12, in entrypoint_main
    H2O_Fire(main)
  File "C:\Users\adria\h2ogpt\src\utils.py", line 64, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "C:\Users\adria\.conda\envs\h2ogpt\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\adria\.conda\envs\h2ogpt\lib\site-packages\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\adria\.conda\envs\h2ogpt\lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\Users\adria\h2ogpt\src\gen.py", line 1344, in main
    max_seq_len = model_state0['tokenizer'].model_max_length
AttributeError: 'NoneType' object has no attribute 'model_max_length'`

**Comment by pseudotensor** [comment]
Sorry was just fixed.  A test fount it too, but didn't complete testing by time the other fix led to this bug.

**Comment by gabriead** [comment]
Hi @pseudotensor, just tried it with latest master branch and the h20ai/h20gpt-4096-llama2-7b-chat and the error is still the same

**Comment by pseudotensor** [comment]
It's impossible to get the same error since the code changed, and it checks for that attribute.

If you give the full command I can run, but I don't think it can hit same issue.

E.g. if I run:
```
python generate.py --base_model=h2oai/h2ogpt-4096-llama2-7b-chat
```
there is no issue.  Your model name is not quite right with 0, but that won't mean it hits that error.

**Comment by gabriead** [comment]
Correct, that works. I have not been starting the application from the command line but from inside my PyCharm editor. But now when I try to upload a document this error is happening:
`to include: ['All'] or set allow_custom_value=True.
  warnings.warn(
Traceback (most recent call last):
  File "C:\Users\adria\.conda\envs\h2ogpt\lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\adria\.conda\envs\h2ogpt\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\adria\.conda\envs\h2ogpt\lib\site-packages\gradio\blocks.py", line 1440, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\adria\.conda\envs\h2ogpt\lib\site-packages\gradio\blocks.py", line 1341, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\adria\.conda\envs\h2ogpt\lib\site-packages\gradio\components\dropdown.py", line 248, in postprocess
    [self._warn_if_invalid_choice(_y) for _y in y]
TypeError: 'Dropdown' object is not iterable
Traceback (most recent call last):
  File "C:\Users\adria\.conda\envs\h2ogpt\lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\adria\.conda\envs\h2ogpt\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\adria\.conda\envs\h2ogpt\lib\site-packages\gradio\blocks.py", line 1440, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\adria\.conda\envs\h2ogpt\lib\site-packages\gradio\blocks.py", line 1341, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\adria\.conda\envs\h2ogpt\lib\site-packages\gradio\components\dropdown.py", line 248, in postprocess
    [self._warn_if_invalid_choice(_y) for _y in y]
TypeError: 'Dropdown' object is not iterable
Traceback (most recent call last):
  File "C:\Users\adria\.conda\envs\h2ogpt\lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\adria\.conda\envs\h2ogpt\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\adria\.conda\envs\h2ogpt\lib\site-packages\gradio\blocks.py", line 1440, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\adria\.conda\envs\h2ogpt\lib\site-packages\gradio\blocks.py", line 1341, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\adria\.conda\envs\h2ogpt\lib\site-packages\gradio\components\dropdown.py", line 248, in postprocess
    [self._warn_if_invalid_choice(_y) for _y in y]
TypeError: 'Dropdown' object is not iterable
C:\Users\adria\.conda\envs\h2ogpt\lib\site-packages\gradio\components\dropdown.py:240: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: dropdown or set allow_custom_value=True.
  warnings.warn(
`

**Comment by pseudotensor** [comment]
Probably your dependencies are off.  Reinstall env or ensure your dependencies like gradio are right version.  Or you are doing something non-standard.
